let state, dictionary={}, active='Situation', requestVersion=0;
const $=id=>document.getElementById(id);
const tabNames={Situation:'상황판'};
let dialogFocus=null, articlePage=0, articlesOpen=false;
function showDialog(){dialogFocus=document.activeElement;const d=$('detail');document.body.classList.add('modal-open');if(typeof d.showModal==='function')d.showModal();else{d.classList.add('legacy-dialog');d.setAttribute('open','');$('dialog-backdrop').hidden=false;$('close-dialog').focus();}}
function closeDialog(){const d=$('detail');if(typeof d.close==='function'&&d.open)d.close();else d.removeAttribute('open');$('dialog-backdrop').hidden=true;document.body.classList.remove('modal-open');if(dialogFocus&&dialogFocus.focus)dialogFocus.focus();}
function currentKST(){return new Date(Date.now()+9*3600000).toISOString().slice(0,16);}
function apiURL(path){return path+'?dataset='+$('dataset').value;}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(x,suffix='')=>x===null||x===undefined?'판단 보류':`${x}${suffix}`;
const label=code=>dictionary[code]||code;
const time=iso=>new Date(iso).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false});
const alertNames={COLLECTION_STALE:'수집 갱신 지연',FRAME_SHIFT:'비판 프레임 변화',RISK_HIGH:'위험 지수 상승',FACT_UNVERIFIED:'공식 원문 확인 필요',AMPLIFICATION_broadcast_top:'방송 주요 뉴스 관측',AMPLIFICATION_portal_main:'포털 메인 관측',AMPLIFICATION_broadcast_general:'방송 일반 보도 관측'};
const amplificationNames={portal_main:'포털 메인',broadcast_top:'방송 주요 뉴스',broadcast_general:'방송 일반 보도'};
const channels={media:'언론',portal:'포털 댓글',community:'커뮤니티',sns:'SNS',broadcast:'방송',official:'공식 자료'};
const tag=(text,style='')=>`<span class="tag ${style}">${esc(text)}</span>`;
const panel=(title,sub,body,wide='')=>`<article class="panel ${wide}"><h2>${esc(title)}</h2><div class="sub">${esc(sub)}</div>${body}</article>`;
const empty=text=>`<div class="empty">${esc(text)}</div>`;
const logic=text=>`<div class="logic"><b>판단 기준</b> ${esc(text)}</div>`;
async function api(path){if(window.radarPagesAPI)return window.radarPagesAPI(path);if(window.RADAR_PREVIEW){const key=path.split('?')[0];if(key==='/api/snapshot')return window.RADAR_PREVIEW.snapshot;return window.RADAR_PREVIEW[key];}const res=await fetch(path);const data=await res.json();if(!res.ok)throw Error(data.error||'조회 실패');return data;}
function documentLogic(r){return logic(SKImpact.judge(r,window.SKImpactReferences||[]).basis);}
function bars(items){return items.map(([name,n,color])=>`<div class="bar-row"><span>${esc(name)}</span><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,n||0))}%;background:${color||'var(--mint)'}"></div></div><b>${n==null?'—':n}</b></div>`).join('');}
function frameChart(){
 const points=state.title_observation.hours.slice(-12),colors=['#087e70','#2e68b6','#a8660c','#bd3857'],codes=['F01','F02','F06','F07'];
 if(!points.length)return empty('今日 12:00 이후 수집 구간이 아직 없습니다.'.replace('今日','오늘'));
 const width=360,step=(width-48)/11,first=Date.parse(points[0].at);
 const slots=Array.from({length:12},(_,i)=>new Date(first+i*3600000).toISOString());
 let svg=`<div class="chart-scroll"><svg class="chart" viewBox="0 0 ${width} 180" role="img" aria-label="12시간 시간별 제목 프레임 비중">`;
 [0,25,50,75,100].forEach(n=>{const y=150-n*1.3;svg+=`<line x1="34" y1="${y}" x2="${width-10}" y2="${y}" stroke="#e4e8ed"/><text x="0" y="${y+4}" fill="#647084" font-size="10">${n}%</text>`;});
 slots.forEach((at,i)=>{svg+=`<text x="${38+i*step}" y="173" text-anchor="middle" fill="#647084" font-size="11">${time(at).slice(0,2)}</text>`;});
 codes.forEach((code,i)=>{let current=[];const draw=()=>{if(current.length>1)svg+=`<polyline points="${current.join(' ')}" stroke="${colors[i]}" stroke-width="2.5" fill="none"/>`;current.forEach(pt=>{const [x,y]=pt.split(',');svg+=`<circle cx="${x}" cy="${y}" r="3" fill="${colors[i]}"/>`;});current=[];};points.forEach((p,j)=>{if(!p.n){draw();return;}current.push(`${38+j*step},${150-(p.shares[code]||0)*130}`);});draw();});
 return svg+'</svg></div><div class="chart-window">'+time(slots[0])+'–'+time(new Date(first+12*3600000).toISOString())+' · 12시간 / 한국 시간</div><div class="legend">'+codes.map((c,i)=>`<span><i style="background:${colors[i]}"></i>${esc(label(c))}</span>`).join('')+'</div>'+points.map(p=>`<div class="hour-row"><b>${time(p.at)}–${time(p.end)}${p.partial?' · 진행 중':''}</b><span>${p.n}건${p.n?' · '+Object.entries(p.counts).map(([c,n])=>`${esc(label(c))} ${n}건`).join(' / '):' · 수집 기사 없음'}</span></div>`).join('');
}
function cards(){let m=state.metrics;return '<section class="cards">'+[
 ['게시 기사',m.published,'수집된 게시물 · 전재 포함','', 'published'],['독립 기사',m.stories,'완전 일치 중복 제거 · 승인 표본','', 'stories']
 ].map(([title,n,sub,c,key])=>`<article class="card"><label>${esc(title)}</label><strong class="${c}">${esc(n)}</strong><small>${esc(sub)}</small>${logic(state.logic[key+'_short']||state.logic[key])}</article>`).join('')+'</section>';}
function summary(){let f=state.shift;return `<div class="summary"><div class="eyebrow mint">관측 요약</div><p>현재 승인 독립 기사 ${state.metrics.stories}건. 프레임 변화 ${val(f.score)} / 비판 프레임 ${val(f.delta_pp,'%p')}. ${state.facts.length?'공식 기준선은 별도 근거에서 확인할 수 있습니다.':'브리핑 원문 검증 전으로 사건 사실 서술을 보류합니다.'}</p><div class="sub">${esc(f.reason)} · 모든 수치는 선택한 필터와 기준 시각 적용</div>${logic(state.logic.shift)}</div>`;}
function companyPanel(){const c=state.title_observation.companies;return panel('회사별 노출','기사 제목의 회사 언급 · 본문 분석과 구분',bars(Object.entries(c).map(([k,v])=>[k==='HYUNDAI'?'현대오일뱅크':k==='SOIL'?'S-OIL':k,v.share]))+Object.entries(c).map(([k,v])=>`<div class="source-state"><span>${esc(k==='HYUNDAI'?'현대오일뱅크':k==='SOIL'?'S-OIL':k)}</span><span>${v.count} / ${v.total}건</span></div>`).join('')+logic('회사명이 제목에 있는 기사 수 ÷ 조회 조건에 해당하는 전체 기사 수 ×100. 한 기사가 여러 회사에 포함될 수 있어 합계가 100%를 넘을 수 있습니다. 책임·부정 판단이나 실제 도달률이 아닙니다.'));}
function narrativePanel(){return panel('온라인 주요 논리','관측 논리 Top 5 · 전체 여론의 대표성 없음',(state.narratives.length?state.narratives.slice(0,5).map((n,i)=>`<div class="rank"><span class="number">0${i+1}</span><div class="info">${esc(label(n.code))}<small>관측 ${n.count}건</small></div><b>${n.share}%</b></div>`).join(''):empty('포털 댓글·커뮤니티·SNS 수집 연결 대기. 네이버 뉴스 검색 API는 댓글과 SNS 내용을 제공하지 않아 주요 논리를 집계할 실제 표본이 없습니다.'))+logic(state.logic.narratives));}
function coverage(){return panel('수집 상태','연결 상태 · 수집 주기 3배 또는 15분 초과 시 지연',(state.sources.map(s=>`<div class="source-state"><span>${esc(s.name)}</span>${tag(s.fresh?(s.id==='naver-search'&&state.collection_coverage&&state.collection_coverage.status!=='ok'?'일부 수집 미완료':'수집 완료'):'미관측 / 지연',s.fresh?'good':'bad')}</div>`).join('')||empty('연결된 소스 없음'))+logic('최근 수집이 성공하고 갱신 허용 시간 이내이면 수집 완료. 네이버 검색 실패·조회 상한은 일부 수집 미완료로 표시합니다. 지정한 검색 범위 기준이며 전체 기사 누락 0건을 뜻하지 않습니다.'));}
function rowsTable(rows){if(!rows.length)return empty('선택한 조건에서 수집된 문서가 없습니다.');return '<div class="document-list">'+rows.map(r=>{const original=r.body_observation?.original_url||r.url;const safe=/^https?:\/\//i.test(original);return `<article class="document-card"><div class="document-meta"><time>${time(r.published_at)}</time><span>${esc(r.source_name)}</span></div>${safe?`<a class="link-button article-original" href="${esc(original)}" target="_blank" rel="noopener noreferrer">${esc(r.title)}</a>`:`<span>${esc(r.title)}</span>`}</article>`;}).join('')+'</div>';}

function render(){if(!state)return;state.title_observation=HeadlineObservation.observe(state.documents,state.at);let body='';
 if(active==='Situation') body='<div class="dashboard-stack">'+panel('주요 프레임 변화','2026.10.07 12:00부터 1시간 간격 · 제목 기준 자동 분류',frameChart()+logic('발행 시각 기준 12:00–13:00, 13:00–14:00 등으로 집계. 프레임별 기사 수 ÷ 해당 시간의 수집 기사 수 ×100. 제목 단어 사전으로 대표 프레임 1개를 잠정 분류하며 미분류도 분모에 포함. 한 화면에 12시간을 표시하며 12개 구간을 초과하면 최근 12개 구간을 표시. 진행 중 구간은 수집 기준 시각까지이며 아직 도래하지 않은 시간은 빈칸으로 표시. 본문 AI 분석·확정 사실이 아닙니다.'))+companyPanel()+coverage()+articlePanel()+panel('SNS','실제 수집 게시물 · 연결 상태 포함',rowsTable(state.documents.filter(r=>r.channel==='sns'))+logic('SNS 소스 연결 대기. 수집 0건은 해당 이슈의 게시물이나 반응이 없다는 뜻이 아닙니다.'))+'</div>';
 $('content').innerHTML=body;$('heading').textContent='D-Issue';document.title=active==='Situation'?'D-Issue':'D-Issue · '+tabNames[active];
 $('updated').textContent=`기준 ${state.at.replace('T',' ').slice(0,16)} KST · 품질 ${state.metrics.coverage}/${state.metrics.sources}`;
 const toggle=$('article-toggle');if(toggle)toggle.addEventListener('click',()=>{articlesOpen=!articlesOpen;render();});document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{articlePage+=Number(b.dataset.page);render();$('article-toggle').scrollIntoView({block:'start'});}));
}
function detail(id){const r=state.documents.find(r=>r.id===id);if(!r)return;$('detail-title').textContent=r.title;const url=/^https?:\/\//i.test(r.url)?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">원문 열기</a>`:'원문 링크 없음 (합성/수입 자료)';$('detail-body').innerHTML=`<div class="detail-row">${tag(r.status||'pending')} ${tag(r.status==='approved'?label(r.primary_frame||'F00'):'분류 대기')} ${tag('Fact Gap: '+(r.fact_gap||'unverifiable'))}${documentLogic(r)}</div><div class="detail-row"><small>발행 / 수집 · content_scope</small>${esc(r.published_at)} / ${esc(r.collected_at)} · ${esc(r.content_scope)}</div><div class="detail-row"><small>분석과 근거</small>Tone ${esc(r.tone)} · Emotion ${esc(r.emotion)} · 논리 ${esc(label(r.argument))}<br>대상 ${esc(r.targets.join(', '))}<br>${r.evidence.map(e=>esc(e.quote)).join('<br>')}</div><div class="detail-row"><small>Secondary / 강도 / 회사별 노출 플래그</small>${esc(r.secondary.map(label).join(", ")||"없음")}<br><div class="detail-text">${esc(JSON.stringify({frames:r.frames,exposure:r.exposure},null,2))}</div></div><div class="detail-row"><small>원문 (미검증 주장일 수 있음)</small><div class="detail-text">${esc(r.body)}</div></div><div class="detail-row"><small>분석 버전 / 승인자 / 공식 기준선 버전</small>${esc(r.model)} / ${esc(r.prompt_version)} / ${esc(r.reviewed_by)} / ${esc(r.fact_version)}</div><div class="detail-row">${url}</div>`;showDialog();}
async function load(){const version=++requestVersion;$('status').textContent='자료를 불러오는 중…';$('content').setAttribute('aria-busy','true');try{let at=$('cutoff').value;if(at)at+=(at.length===16?':00':'')+'+09:00';let query=new URLSearchParams({dataset:$('dataset').value,hours:$('hours').value,channel:$('channel').value,q:$('search').value});if(at)query.set('at',at);let data=await api('/api/snapshot?'+query);if(version!==requestVersion)return;state=data;articlePage=0;$('status').textContent=window.RADAR_PREVIEW?'Safari 검수용 고정 예시 · 조회 조건 변경 불가':'';$('content').setAttribute('aria-busy','false');render();}catch(e){if(version!==requestVersion)return;$('content').setAttribute('aria-busy','false');$('content').innerHTML=empty('자료를 불러오지 못했습니다. 조회를 다시 눌러 주세요.');$('status').textContent='조회 실패: '+e.message;}}
$('refresh').addEventListener('click',load);['hours','channel'].forEach(id=>$(id).addEventListener('change',load));$('search').addEventListener('keydown',e=>{if(e.key==='Enter')load();});$('close-dialog').addEventListener('click',closeDialog);$('dialog-backdrop').addEventListener('click',closeDialog);$('detail').addEventListener('close',()=>{document.body.classList.remove('modal-open');});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('detail').hasAttribute('open'))closeDialog();});$('dataset').addEventListener('change',()=>{$('cutoff').value=$('dataset').value==='demo'?'2026-10-07T21:30':currentKST();load();});
$('report').addEventListener('click',async()=>{try{const reports=await api(apiURL('/api/reports'));$('detail-title').textContent='정시 상황보고 · 초안';$('detail-body').innerHTML=reports.length?reports.map(r=>`<div class="detail-text">${esc(r.body)}</div><hr>`).join(''):empty('보고 생성 작업을 실행하면 12/15/18/21:30 보고 초안이 여기에 표시됩니다.');showDialog();}catch(e){$('status').textContent=e.message;}});
(async()=>{try{const [f,h]=await Promise.all([api('/api/frames'),api('/api/health')]);dictionary=Object.fromEntries(f.frames.map(x=>[x.code,x.label]));if(h.mode!=='demo'){$('dataset').value='live';$('cutoff').value=currentKST();}await load();}catch(e){$('status').textContent='초기화 실패: '+e.message;}})();

$('readiness').addEventListener('click',async()=>{try{const r=await api('/api/readiness');$('detail-title').textContent='실제 데이터 연결';$('detail-body').innerHTML=r.steps.map(x=>`<div class="detail-row"><strong>${esc(x.label)}</strong> ${tag(x.url?'연결됨':x.ready?'준비됨':'연결 필요',x.ready?'good':'bad')}<small>${esc(x.note)}</small>${x.url&&/^https:\/\//i.test(x.url)?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">공식 브리핑 열기 ↗</a>`:''}</div>`).join('')+`<div class="detail-row">수집 문서 ${r.documents}건 · 승인 ${r.approved}건 · 분석 대기 ${r.pending}건<br>다음 단계: ${esc(r.next_action)}</div>`;showDialog();}catch(e){$('status').textContent=e.message;}});

if(window.RADAR_PREVIEW){["dataset","hours","channel","search","cutoff","refresh"].forEach(id=>$(id).disabled=true);$("status").textContent="Safari 검수용 고정 예시 · 데이터 조회 조건 변경 불가";}

if(window.RADAR_PAGES)setInterval(()=>{if(!document.hidden)load();},120000);

function coverageRows(c){return `<p>네이버: ${esc(c.status)} · 조회 ${c.requests||0}회 · 기준 ${esc(c.since||'미설정')}</p>`+(c.queries||[]).map(q=>`<div class="detail-row"><strong>${esc(q.query)}</strong><br>검색 총 ${q.reported_total??'미확인'} · 실제 조회 ${q.scanned} · 중복 제외 URL ${q.unique_urls} · 기준일 이후 ${q.in_scope} · 신규 ${q.new} · ${q.pages}페이지${logic(({results_end_reached:'API가 반환한 검색 결과 끝까지 조회.',scope_boundary_reached:'날짜순 조회가 기준일 이전 기사에 도달해 중단.',api_limit:'API 조회 상한 도달. 누락 가능성이 있어 보완 검색 필요.',budget_limit:'호출 예산 상한 도달. 미조회 범위 있음.',failed:'요청 실패. 전체 조회 완료로 표시하지 않음.'})[q.status]||q.status)}</div>`).join('')+logic(c.scope||'키 연결 전으로 조회 범위 미확인.');}

function articlePanel(){
 const rows=state.documents.filter(r=>r.channel==='media').slice().sort((a,b)=>Date.parse(b.published_at)-Date.parse(a.published_at)),pages=Math.max(1,Math.ceil(rows.length/30));articlePage=Math.max(0,Math.min(articlePage,pages-1));
 const control=`<button id="article-toggle" aria-expanded="${articlesOpen}" aria-controls="article-items">${articlesOpen?'▲ 목록 접기':'▼ 기사 목록 펼치기'} · ${rows.length}건</button>`;
 const list=articlesOpen?`<div id="article-items">${rowsTable(rows.slice(articlePage*30,articlePage*30+30))}<div class="pagination"><button data-page="-1" ${articlePage===0?'disabled':''}>이전</button><span>${articlePage+1} / ${pages}페이지 · 30개씩</span><button data-page="1" ${articlePage===pages-1?'disabled':''}>다음</button></div></div>`:'';
 return panel('수집 기사','최신 발행순 · 페이지당 30개',control+list);
}

$('back-top').addEventListener('click',()=>{window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});
