let state, dictionary={}, active='Situation', requestVersion=0;
const $=id=>document.getElementById(id);
const tabNames={Situation:'상황판',Timeline:'시간 흐름',Media:'언론',Public:'온라인',Spread:'확산',Watch:'확인 과제'};
let dialogFocus=null;
function showDialog(){dialogFocus=document.activeElement;const d=$('detail');document.body.classList.add('modal-open');if(typeof d.showModal==='function')d.showModal();else{d.classList.add('legacy-dialog');d.setAttribute('open','');$('dialog-backdrop').hidden=false;$('close-dialog').focus();}}
function closeDialog(){const d=$('detail');if(typeof d.close==='function'&&d.open)d.close();else d.removeAttribute('open');$('dialog-backdrop').hidden=true;document.body.classList.remove('modal-open');if(dialogFocus&&dialogFocus.focus)dialogFocus.focus();}
function currentKST(){return new Date(Date.now()+9*3600000).toISOString().slice(0,16);}
function apiURL(path){return path+'?dataset='+$('dataset').value;}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(x,suffix='')=>x===null||x===undefined?'판단 보류':`${x}${suffix}`;
const label=code=>dictionary[code]||code;
const time=iso=>new Date(iso).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false});
const alertNames={COLLECTION_STALE:'수집 갱신 지연',FRAME_SHIFT:'비판 프레임 변화',RISK_HIGH:'위험 지수 상승',FACT_UNVERIFIED:'공식 원문 확인 필요',AMPLIFICATION_broadcast_top:'방송 주요 뉴스 관측',AMPLIFICATION_portal_main:'포털 메인 관측',AMPLIFICATION_broadcast_general:'방송 일반 보도 관측'};
const amplificationNames={portal_main:'포털 메인',broadcast_top:'방송 주요 뉴스',broadcast_general:'방송 일반 보도'};
const channels={media:'언론',portal:'포털 댓글',community:'커뮤니티',sns:'SNS',broadcast:'방송',official:'공식 자료'};
const tag=(text,style='')=>`<span class="tag ${style}">${esc(text)}</span>`;
const panel=(title,sub,body,wide='')=>`<article class="panel ${wide}"><h2>${esc(title)}</h2><div class="sub">${esc(sub)}</div>${body}</article>`;
const empty=text=>`<div class="empty">${esc(text)}</div>`;
const logic=text=>`<div class="logic"><b>판단 기준</b> ${esc(text)}</div>`;
async function api(path){if(window.radarPagesAPI)return window.radarPagesAPI(path);if(window.RADAR_PREVIEW){const key=path.split('?')[0];if(key==='/api/snapshot')return window.RADAR_PREVIEW.snapshot;return window.RADAR_PREVIEW[key];}const res=await fetch(path);const data=await res.json();if(!res.ok)throw Error(data.error||'조회 실패');return data;}
function documentLogic(r){return logic(r.status==='approved'?`원문 인용을 프레임 사전과 대조한 분류 · 담당자 ${r.reviewed_by||'미기재'} 승인 · 분석 신뢰도 ${r.confidence}. ${r.evidence.map(e=>e.quote).join(' / ')}. 사건 사실의 확정 판단이 아님.`:'미승인 자료로 지수 계산에서 제외. 원문·프레임·근거 검토 후 반영.');}
function bars(items){return items.map(([name,n,color])=>`<div class="bar-row"><span>${esc(name)}</span><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,n||0))}%;background:${color||'var(--mint)'}"></div></div><b>${n==null?'—':n}</b></div>`).join('');}
function frameChart(){
 const colors=['#087e70','#2e68b6','#a8660c','#bd3857'],codes=['F01','F03','F06','F07'];
 let svg='<svg class="chart" viewBox="0 0 560 180" role="img" aria-label="시간별 주요 프레임 점유율">';
 [0,25,50,75,100].forEach(n=>{let y=150-n*1.3;svg+=`<line x1="34" y1="${y}" x2="542" y2="${y}" stroke="#e4e8ed"/><text x="0" y="${y+4}" fill="#647084" font-size="9">${n}%</text>`;});
 state.trend.forEach((p,i)=>{svg+=`<text x="${39+i*96}" y="173" fill="#647084" font-size="9">${time(p.at)}</text>`;});
 codes.forEach((code,i)=>{let segments=[],current=[];state.trend.forEach((p,j)=>{if(p.n<20){if(current.length)segments.push(current);current=[];return;}current.push(`${52+j*96},${150-(p.shares[code]||0)*130}`);});if(current.length)segments.push(current);segments.forEach(points=>{if(points.length>1)svg+=`<polyline points="${points.join(' ')}" stroke="${colors[i]}" stroke-width="2.5" fill="none"/>`;points.forEach(pt=>{let [x,y]=pt.split(',');svg+=`<circle cx="${x}" cy="${y}" r="3" fill="${colors[i]}"/>`;});});});
 return svg+'</svg><div class="legend">'+codes.map((c,i)=>`<span><i style="background:${colors[i]}"></i>${esc(label(c))}</span>`).join('')+'</div>';
}
function cards(){let m=state.metrics;return '<section class="cards">'+[
 ['게시 기사',m.published,'수집된 게시물 · 전재 포함','', 'published'],['독립 기사',m.stories,'완전 일치 중복 제거 · 승인 표본','', 'stories'],['SK 노출 지수',val(state.companies.SK.score),'0–100 · 노출 강도 지표','mint','exposure'],['관측 표본 부정',val(m.negative,'%'),`댓글·게시물 n=${m.public_sample}`,'orange','negative'],['위험 지수',val(m.risk),m.risk_reason,'pink','risk']
 ].map(([title,n,sub,c,key])=>`<article class="card"><label>${esc(title)}</label><strong class="${c}">${esc(n)}</strong><small>${esc(sub)}</small>${logic(state.logic[key+'_short']||state.logic[key])}</article>`).join('')+'</section>';}
function summary(){let f=state.shift;return `<div class="summary"><div class="eyebrow mint">관측 요약</div><p>현재 승인 독립 기사 ${state.metrics.stories}건. 프레임 변화 ${val(f.score)} / 비판 프레임 ${val(f.delta_pp,'%p')}. ${state.facts.length?'공식 기준선은 별도 근거에서 확인할 수 있습니다.':'브리핑 원문 검증 전으로 사건 사실 서술을 보류합니다.'}</p><div class="sub">${esc(f.reason)} · 모든 수치는 선택한 필터와 기준 시각 적용</div>${logic(state.logic.shift)}</div>`;}
function companyPanel(){return panel('회사별 노출','동일 독립 기사 표본 / 0–100 · 언급이 없는 회사는 0',bars(Object.entries(state.companies).map(([k,v])=>[k==='HYUNDAI'?'현대오일뱅크':k,v.score]))+logic(state.logic.exposure));}
function narrativePanel(){return panel('온라인 주요 논리','관측 논리 Top 5 · 전체 여론의 대표성 없음',(state.narratives.length?state.narratives.slice(0,5).map((n,i)=>`<div class="rank"><span class="number">0${i+1}</span><div class="info">${esc(label(n.code))}<small>관측 ${n.count}건</small></div><b>${n.share}%</b></div>`).join(''):empty('연결된 온라인 표본이 없습니다.'))+logic(state.logic.narratives));}
function coverage(){return panel('수집 상태','연결 상태 · 수집 주기 3배 또는 15분 초과 시 지연',(state.sources.map(s=>`<div class="source-state"><span>${esc(s.name)}</span>${tag(s.fresh?'관측 신선':'미관측 / 지연',s.fresh?'good':'bad')}</div>`).join('')||empty('연결된 소스 없음'))+logic(state.logic.coverage));}
function rowsTable(rows){if(!rows.length)return empty('선택한 조건에서 수집된 문서가 없습니다.');return '<div class="document-list">'+rows.map(r=>`<article class="document-card"><div class="document-meta"><time>${time(r.published_at)}</time><span>${esc(r.source_name)}</span><span>${esc(channels[r.channel])}</span></div><button class="link-button" data-doc="${esc(r.id)}">${esc(r.title)}</button><div class="document-tags">${tag(r.status==='approved'?label(r.primary_frame||'F00'):'분류 대기')}${tag(r.status==='approved'?'승인':'검토 대기',r.status==='approved'?'good':'bad')}${tag({full:'본문',snippet:'검색 요약',title:'제목',transcript:'방송 전사',comment:'댓글'}[r.content_scope]||r.content_scope)}</div>${documentLogic(r)}</article>`).join('')+'</div>';}
function render(){if(!state)return;let body='';
 if(active==='Situation') body=cards()+summary()+(window.RADAR_PAGES?panel('최근 수집 기사','공개 RSS 제목·매체·링크 · 분석 검토 대기',rowsTable(state.documents.filter(r=>r.channel==='media').slice(0,6))):'')+'<div class="grid">'+panel('주요 프레임 변화','직전 6개 60분 창 · primary 점유율 · n<20 구간 숨김',frameChart()+logic(state.logic.frames))+companyPanel()+narrativePanel()+coverage()+'</div>';
 if(active==='Timeline')body=panel('시간별 흐름','발행 시각 KST · 수집 시각은 상세에서 별도 표시',state.documents.map(r=>`<div class="event"><time>${time(r.published_at)}</time><div><p><button class="link-button" data-doc="${esc(r.id)}">${esc(r.title)}</button></p>${tag(channels[r.channel])} ${tag(r.status==='approved'?label(r.primary_frame||'F00'):'분류 대기')} <small>${esc(r.status||'pending')}</small>${documentLogic(r)}</div></div>`).join('')||empty('관측 이벤트 없음'));
 if(active==='Media')body=cards()+panel('언론 분석','클릭하면 원문 증거·프레임·Fact Gap·버전·회사 노출 근거를 확인합니다.',rowsTable(state.documents.filter(r=>r.channel==='media')));
 if(active==='Public')body='<div class="grid">'+narrativePanel()+panel('논리별 대표 관측','사용자 이름·프로필은 저장하지 않습니다. 표본 선정 편향을 함께 검토하세요.',state.narratives.map(n=>`<div class="watch"><strong>${esc(label(n.code))} · ${n.share}%</strong>${logic(state.logic.narratives)}${n.examples.map(e=>`<p>${esc(e.quote)}</p>`).join('')}</div>`).join('')||empty('댓글·게시물 수집 없음'))+panel('온라인 관측 자료','감정·논리·대상은 문서 상세에서 확인',rowsTable(state.documents.filter(r=>['portal','community','sns'].includes(r.channel))),'wide')+'</div>';
 if(active==='Spread')body='<div class="grid">'+panel('포털·방송 관측','노출 증거가 확인된 관측 · 도달 인원이나 인과 효과로 해석하지 않습니다.',state.amplifications.map(a=>`<div class="event"><time>${time(a.observed_at)}</time><div><p>${esc(amplificationNames[a.kind]||a.kind)}</p>${tag(a.duration_basis==='point_observation'?'시점 관측':a.duration_basis)}<p><small>${esc(a.evidence_uri)}</small></p></div></div>`).join('')||empty('이 시간창에서 증빙된 증폭 이벤트 없음'))+coverage()+panel('방송 분석','전사/자막의 앵커·기자·인용 발언을 구분하는 분석은 상세 원문 기준',rowsTable(state.documents.filter(r=>r.channel==='broadcast')),'wide')+'</div>';
 if(active==='Watch')body='<div class="grid">'+(state.collection_coverage?panel('검색별 수집 범위','네이버 검색 결과 범위의 조회 기록 · 전체 언론의 누락 0건을 의미하지 않음',coverageRows(state.collection_coverage),'wide'):'')+panel('확인할 신호','표본·증빙 조건 충족 관측 신호 / 외부 전송 없음',state.alerts.map(a=>`<div class="watch ${a.severity}">${tag(({high:'주의',watch:'검토',quality:'자료 확인'})[a.severity]||a.severity,a.severity==='high'?'bad':'')}<strong>${esc(alertNames[a.rule]||a.rule)}</strong><p>${esc(a.text)}</p>${logic(a.logic)}<small>근거 ID: ${esc(a.evidence.join(', ')||'없음')}</small></div>`).join('')||empty('조건을 충족한 알림 없음'))+panel('공식 사실과 보도 프레임','공식 사실은 원문/페이지 증거와 담당자 승인 이후 표시',state.facts.length?state.facts.map(f=>`<div class="detail-row">${esc(f.statement)}<small>${esc(f.procedural_status)} · v${f.version} · ${esc(f.locator)}</small></div>`).join(''):empty('승인된 공식 사실 0건. 이전 대화의 수치는 원문 확인 대기이며 공식 사실로 등록하지 않았습니다.'))+panel('판단 시 유의사항','데이터 품질과 지표 해석',state.limitations.map(t=>`<div class="detail-row">${esc(t)}</div>`).join(''),'wide')+'</div>';
 $('content').innerHTML=body;$('heading').textContent='D-Issue';document.title=active==='Situation'?'D-Issue':'D-Issue · '+tabNames[active];
 $('mode').textContent=state.mode==='demo'?'합성 예시':'실제 자료';
 $('notice').textContent=(state.mode==='demo'?'합성 예시 · 실제 자료가 아닙니다. ':'실제 수집 자료 · 관측 표본 기준입니다. ')+(state.facts.length?'공식 사실과 보도 프레임을 구분합니다.':'공식 브리핑 원문 확인 대기. 기사 제목은 언론의 표현이며 사건의 확정 사실이 아닙니다.');
 $('updated').textContent=`기준 ${state.at.replace('T',' ').slice(0,16)} KST · 품질 ${state.metrics.coverage}/${state.metrics.sources}`;
 document.querySelectorAll('[data-doc]').forEach(b=>b.addEventListener('click',()=>detail(b.dataset.doc)));
}
function detail(id){const r=state.documents.find(r=>r.id===id);if(!r)return;$('detail-title').textContent=r.title;const url=/^https?:\/\//i.test(r.url)?`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">원문 열기</a>`:'원문 링크 없음 (합성/수입 자료)';$('detail-body').innerHTML=`<div class="detail-row">${tag(r.status||'pending')} ${tag(r.status==='approved'?label(r.primary_frame||'F00'):'분류 대기')} ${tag('Fact Gap: '+(r.fact_gap||'unverifiable'))}${documentLogic(r)}</div><div class="detail-row"><small>발행 / 수집 · content_scope</small>${esc(r.published_at)} / ${esc(r.collected_at)} · ${esc(r.content_scope)}</div><div class="detail-row"><small>분석과 근거</small>Tone ${esc(r.tone)} · Emotion ${esc(r.emotion)} · 논리 ${esc(label(r.argument))}<br>대상 ${esc(r.targets.join(', '))}<br>${r.evidence.map(e=>esc(e.quote)).join('<br>')}</div><div class="detail-row"><small>Secondary / 강도 / 회사별 노출 플래그</small>${esc(r.secondary.map(label).join(", ")||"없음")}<br><div class="detail-text">${esc(JSON.stringify({frames:r.frames,exposure:r.exposure},null,2))}</div></div><div class="detail-row"><small>원문 (미검증 주장일 수 있음)</small><div class="detail-text">${esc(r.body)}</div></div><div class="detail-row"><small>분석 버전 / 승인자 / 공식 기준선 버전</small>${esc(r.model)} / ${esc(r.prompt_version)} / ${esc(r.reviewed_by)} / ${esc(r.fact_version)}</div><div class="detail-row">${url}</div>`;showDialog();}
async function load(){const version=++requestVersion;$('status').textContent='자료를 불러오는 중…';$('content').setAttribute('aria-busy','true');try{let at=$('cutoff').value;if(at)at+=(at.length===16?':00':'')+'+09:00';let query=new URLSearchParams({dataset:$('dataset').value,hours:$('hours').value,channel:$('channel').value,q:$('search').value});if(at)query.set('at',at);let data=await api('/api/snapshot?'+query);if(version!==requestVersion)return;state=data;$('status').textContent=window.RADAR_PREVIEW?'Safari 검수용 고정 예시 · 조회 조건 변경 불가':'';$('content').setAttribute('aria-busy','false');render();}catch(e){if(version!==requestVersion)return;$('content').setAttribute('aria-busy','false');$('content').innerHTML=empty('자료를 불러오지 못했습니다. 조회를 다시 눌러 주세요.');$('status').textContent='조회 실패: '+e.message;}}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.tab;document.querySelectorAll('.nav').forEach(n=>{n.classList.toggle('active',n===b);if(n===b)n.setAttribute('aria-current','page');else n.removeAttribute('aria-current');});render();}));
$('refresh').addEventListener('click',load);['hours','channel'].forEach(id=>$(id).addEventListener('change',load));$('search').addEventListener('keydown',e=>{if(e.key==='Enter')load();});$('close-dialog').addEventListener('click',closeDialog);$('dialog-backdrop').addEventListener('click',closeDialog);$('detail').addEventListener('close',()=>{document.body.classList.remove('modal-open');});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('detail').hasAttribute('open'))closeDialog();});$('dataset').addEventListener('change',()=>{$('cutoff').value=$('dataset').value==='demo'?'2026-10-07T21:30':currentKST();load();});
$('report').addEventListener('click',async()=>{try{const reports=await api(apiURL('/api/reports'));$('detail-title').textContent='정시 상황보고 · 초안';$('detail-body').innerHTML=reports.length?reports.map(r=>`<div class="detail-text">${esc(r.body)}</div><hr>`).join(''):empty('보고 생성 작업을 실행하면 12/15/18/21:30 보고 초안이 여기에 표시됩니다.');showDialog();}catch(e){$('status').textContent=e.message;}});
(async()=>{try{const [f,h]=await Promise.all([api('/api/frames'),api('/api/health')]);dictionary=Object.fromEntries(f.frames.map(x=>[x.code,x.label]));if(h.mode!=='demo'){$('dataset').value='live';$('cutoff').value=currentKST();}await load();}catch(e){$('status').textContent='초기화 실패: '+e.message;}})();

$('readiness').addEventListener('click',async()=>{try{const r=await api('/api/readiness');$('detail-title').textContent='실제 데이터 연결';$('detail-body').innerHTML=r.steps.map(x=>`<div class="detail-row"><strong>${esc(x.label)}</strong> ${tag(x.ready?'준비됨':'연결 필요',x.ready?'good':'bad')}<small>${esc(x.note)}</small></div>`).join('')+`<div class="detail-row">수집 문서 ${r.documents}건 · 승인 ${r.approved}건 · 분석 대기 ${r.pending}건<br>다음 단계: ${esc(r.next_action)}</div>`;showDialog();}catch(e){$('status').textContent=e.message;}});

if(window.RADAR_PREVIEW){["dataset","hours","channel","search","cutoff","refresh"].forEach(id=>$(id).disabled=true);$("status").textContent="Safari 검수용 고정 예시 · 데이터 조회 조건 변경 불가";}

if(window.RADAR_PAGES)setInterval(()=>{if(!document.hidden)load();},120000);

function coverageRows(c){return `<p>네이버: ${esc(c.status)} · 조회 ${c.requests||0}회 · 기준 ${esc(c.since||'미설정')}</p>`+(c.queries||[]).map(q=>`<div class="detail-row"><strong>${esc(q.query)}</strong><br>검색 총 ${q.reported_total??'미확인'} · 실제 조회 ${q.scanned} · 중복 제외 URL ${q.unique_urls} · 기준일 이후 ${q.in_scope} · 신규 ${q.new} · ${q.pages}페이지${logic(({results_end_reached:'API가 반환한 검색 결과 끝까지 조회.',scope_boundary_reached:'날짜순 조회가 기준일 이전 기사에 도달해 중단.',api_limit:'API 조회 상한 도달. 누락 가능성이 있어 보완 검색 필요.',budget_limit:'호출 예산 상한 도달. 미조회 범위 있음.',failed:'요청 실패. 전체 조회 완료로 표시하지 않음.'})[q.status]||q.status)}</div>`).join('')+logic(c.scope||'키 연결 전으로 조회 범위 미확인.');}
